require: rubocop-rspec

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/environments/*.rb'
    - 'bin/*'

Rails:
  Enabled: true

Documentation:
    Enabled: false

Rails/Output:
  Enabled: false

Style/DateTime:
  Enabled: true

Metrics/LineLength:
  Max: 130
  Exclude:
    - 'initializers/simple_form.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'